name: tic_tac_toe
description: A new Flutter application.

publish_to:
version: 1.0.0+1

environment:
  sdk: '3.7.2'

dependencies:
  flutter:
    sdk: flutter

cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true